### ISSUE TITLE
Linux package for ssh access

### ISSUE THREAD

**Issue by atombaby** [fhdsl/FH_Cluster_Guide#24]
For ubuntu, the necessary package is _openssh-client_ (not _-server_).  I'm not sure if we want to get into the weeds with other distribution package names.

https://github.com/fhdsl/FH_Cluster_Guide/blob/7e20de40058ad951031afea2733c381ed33b432d/docs/terminal.html#L239

**Comment by carriewright11** [comment]
Looks like this is in the 01-101.Rmd file

**Comment by atombaby** [comment]
Yup- not sure how I missed it with my search!

https://github.com/fhdsl/FH_Cluster_Guide/blob/7e20de40058ad951031afea2733c381ed33b432d/01-101.Rmd#L134

**Comment by carriewright11** [comment]
It was a bit tricky with the subsections being inside that file.

> Yup- not sure how I missed it with my search!
> 
> https://github.com/fhdsl/FH_Cluster_Guide/blob/7e20de40058ad951031afea2733c381ed33b432d/01-101.Rmd#L134

It was a bit tricky with the subsections being inside that file!

**Comment by avahoffman** [comment]
@atombaby Thank you for catching this! I can also split up the Rmd sections if that makes it easier to review!
