### ISSUE TITLE
use fhR/* modules instead of R/* modules

### ISSUE THREAD

**Issue by dtenenba** [fhdsl/FH_Cluster_Guide#33]
https://hutchdatascience.org/FH_Cluster_Guide/interactive-session.html says to load `R/4.2.0-foss-2021b`. It's always best to load R modules that start with `fhR` (such as `fhR/4.2.0-foss-2021b`). These modules include hundreds (thousands?) of pre-built R packages which users have requested over the years. If they load `R/*` modules they may not realize these packages are available, and will try and install them themselves, which is not always a simple process.

(BTW, though you don't reference python in the course, the same holds true for Python - use fhPython/* modules instead of Python/* modules).

**Comment by avahoffman** [comment]
Good to know, thanks!!
