### ISSUE TITLE
clicking link leads to TOC-less page

### ISSUE THREAD

**Issue by dtenenba** [fhdsl/FH_Cluster_Guide#35]
Hi, if I go to https://hutchdatascience.org/FH_Cluster_Guide/faq-and-troubleshooting.html and click the link at the bottom that says "use the form mentioned in the course" it takes me to https://hutchdatascience.org/FH_Cluster_Guide/01-101.html#pi-account but I think it should go to https://hutchdatascience.org/FH_Cluster_Guide/account-setup.html#pi-account .
The page it takes me to looks like it's not fully rendered to markdown and does not have the TOC or navigation buttons.

**Comment by avahoffman** [comment]
Good catch!
