### ISSUE TITLE
Change in functionality of edit button?

### ISSUE THREAD

**Issue by dtenenba** [fhdsl/FH_Cluster_Guide#38]
When I click the edit button on a page it takes me to a page that says I have to fork the repo before I can edit a page.

And if I am not signed into GitHub I have to sign in first - and I may not even have an account. 

In the SciWiki, if you click the "Edit this page via GitHub" button at the top of any page (e.g. https://sciwiki.fredhutch.org/generation/gen_index/ ) it takes you to (e.g.) https://github.com/FredHutch/wiki/blob/main/_generation/gen_index.md which will work even if you are not logged into github and have not forked the repo. From there you can click the little pencil icon and edit the page (this does require that you be logged in, but if you are, it will create the fork for you). 

Also, I usually right click on a link and chose "Open in new tab" but that does not work with the edit button, probably because it runs some javascript. 

Finally, for those who may not be up for forking and making PRs, could there be a "report problem" link that takes you to the [new issue page](https://github.com/fhdsl/FH_Cluster_Guide/issues/new/choose)?

BTW please pardon this flurry of issues. I think the course is awesome - I just need to report each minor thing I find. 
😀

**Comment by avahoffman** [comment]
> When I click the edit button on a page it takes me to a page that says I have to fork the repo before I can edit a page.
> 
> And if I am not signed into GitHub I have to sign in first - and I may not even have an account.
> 
> In the SciWiki, if you click the "Edit this page via GitHub" button at the top of any page (e.g. https://sciwiki.fredhutch.org/generation/gen_index/ ) it takes you to (e.g.) https://github.com/FredHutch/wiki/blob/main/_generation/gen_index.md which will work even if you are not logged into github and have not forked the repo. From there you can click the little pencil icon and edit the page (this does require that you be logged in, but if you are, it will create the fork for you).
> 
> Also, I usually right click on a link and chose "Open in new tab" but that does not work with the edit button, probably because it runs some javascript.

Excellent points! Will work on a fix for this.

> Finally, for those who may not be up for forking and making PRs, could there be a "report problem" link that takes you to the [new issue page](https://github.com/fhdsl/FH_Cluster_Guide/issues/new/choose)?

Do you think we could use something in addition to this page? https://hutchdatascience.org/FH_Cluster_Guide/feedback.html

> BTW please pardon this flurry of issues. I think the course is awesome - I just need to report each minor thing I find. 😀

Keep them coming! These have been so so helpful! 🙌🏻

**Comment by avahoffman** [comment]
Resolved by #47
